name: "Run Challenge Tests"
description: "Runs tests for a specific challenge and posts results to the PR."

on:
  workflow_call:
    inputs:
      challengeId:
        required: true
        type: string
    secrets:
      PRIVATE_REPO_PAT:
        required: true

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Debug PRIVATE_REPO_PAT
        run: |
          if [ -z "${{ secrets.PRIVATE_REPO_PAT }}" ]; then
            echo "⛔ PRIVATE_REPO_PAT is EMPTY"
            exit 1
          else
            echo "✅ PRIVATE_REPO_PAT is SET"
          fi

      # 1) checkout del codice candidato (il template-repo)
      - uses: actions/checkout@v3

      # 2) checkout del repo privato dei test
      - name: Checkout hiring-tests
        uses: actions/checkout@v3
        with:
          repository: doublebitsrl/hiring-tests
          path: hiring-tests
          token: ${{ secrets.PRIVATE_REPO_PAT }}

      # ← NUOVO STEP: copio il tuo stub src/tracker.js dentro hiring-tests/src
      - name: Copy tracker stub into hiring-tests
        run: |
          mkdir -p hiring-tests/src
          cp src/tracker.js hiring-tests/src/tracker.js

      # 3) install dei test
      - name: Install hiring-tests dependencies
        run: |
          cd hiring-tests
          npm ci

      # 4) esecuzione tests per il challenge specifico
      - name: Run challenge tests
        run: |
          cd hiring-tests
          npm run test:ci -- --testPathPattern="tests/${{ inputs.challengeId }}/"

      # 5) pubblica report su PR
      - name: Comment PR with report
        if: always()
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          path: hiring-tests/report.json
          header: "## Risultati Test – ${{ inputs.challengeId }}"
